version: '1.0'
networks:
  myapp:
    name: myapp
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: myapp-zookeeper
    networks:
      - myapp
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: myapp-kafka
    networks:
      - myapp
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - 'KAFKA_LISTENERS=PLAINTEXT://:9092'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # Spark Master
  spark:
    image: 'bitnami/spark:latest'
    container_name: myapp-spark-master
    networks:
      - myapp
    ports:
      - '8080:8080'
    environment:
      - SPARK_MODE=master
    volumes:
      - '/Users/adisonpereiradeoliveira/Desktop/mytable/CRYPTO-VIZ/spark:/opt/bitnami/spark/work'
#    command: sh -c "pip install -r requirements.txt && cd /opt/bitnami/spark/work && python script.py"

  spark_worker:
    image: 'bitnami/spark:latest'
    container_name: myapp-spark-worker
    networks:
      - myapp
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    volumes:
      - '/Users/adisonpereiradeoliveira/Desktop/mytable/CRYPTO-VIZ/spark:/opt/bitnami/spark/work'
    
    
