version: '1.0'
networks:
  myapp:
    name: myapp
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: myapp-zookeeper
    networks:
      - myapp
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: myapp-kafka
    networks:
      - myapp
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - 'KAFKA_LISTENERS=PLAINTEXT://:9092'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
